### ISSUE TITLE
1inch did implement a migration from uniswap->mooniswap, you may use this code somewhere

### ISSUE THREAD

**Issue by martinkrung** [sushiswap/sushiswap#1]
It's based on my inspiration of migration mining and you implemented a form of it. I did not see larrys tweet until today!

https://www.cryptonative.ch/migration-mining-mm-a-new-form-of-incentive-for-crypto-projects-to-get-liquidity-into-a-liquidity-dependent-protocol/

Here the code, (MIT)
https://github.com/CryptoManiacsZone/1inchProtocol/blob/feature/mooniswap-migration/contracts/OneSplitMooniswapMigration.sol

And you just implemented the vampire attack: https://twitter.com/martinkrung/status/1298363320270032897?s=20

**Comment by aak-dev** [comment]
Liquidity wars are on!

**Comment by martinkrung** [comment]
Yes, don't like the way the chef handled this:
https://twitter.com/martinkrung/status/1302229884874436608?s=20
https://twitter.com/ameensol/status/1302395863709351936?s=20
