### ISSUE TITLE
Yield farms and sushibar not working on [FANTOM]

### ISSUE THREAD

**Issue by mmmmyah** [sushiswap/sushiswap#100]
Please add yield farms and sushibar on the Fantom chain. It seems like only Sushi Swap works on Fantom. I can't find the Yield and Sushibar top navigation bar items (like I do on ethereum) and the following URLs just redirect to swap ..
https://app.sushi.com/yield
https://app.sushi.com/sushibar

Getting a lot of requests for sushi farms on Fantom .. please add!!! thanks!!!!

**Comment by omakasebar** [comment]
There are no incentivized yield farms at the moment on Fantom. Staking sushi for xsushi only works on Mainnet currently. Please open future requests here: https://github.com/sushiswap/sushiswap-interface/issues
