### ISSUE TITLE
Harvest button on SushiSwap Yield - MATIC - does not work

### ISSUE THREAD

**Issue by Gondee** [sushiswap/sushiswap#101]
I am using the ETH/USDT pool on Sushi Yield tab on MATIC. rewards show properly, but clicking the Harvest button does not seem to do anything. I tried 2 different RPC's but no luck. It seems that Meta Mask is not called and or does not generate the TX, leading me to believe its a api interaction issue.

Here is the console log when clicking the button: 
![image](https://user-images.githubusercontent.com/5413555/119236307-54132d80-bafc-11eb-9501-59ff79bd37db.png)

Discussion around users with the issue on discord: 
https://discord.com/channels/748031363935895552/749850975581241374/845719364028203060

**Comment by omakasebar** [comment]
Closing, op will repost at correct repo: https://github.com/sushiswap/sushiswap-interface/issues
