### ISSUE TITLE
What is the init code hash of sushiswap?

### ISSUE THREAD

**Issue by 3mp8r3** [sushiswap/sushiswap#115]

**Comment by 3mp8r3** [comment]
What is the init code hash of sushiswap?

**Comment by shabamirims** [comment]
0x34a26ac00aeedff252c746538fd4d97e26d9bc7e1d5a32b31c6e3cdea7c6147d

**Comment by ianmaddox** [comment]
> Since this is the n°1 result on Google for this query here is the SushiSwapV2Factory ( 0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac ) init code hash: 0xe18a34eb0e04b04f7a0ac29a6e80748dca96319b42c54d679cb821dca90c6303

This is the correct answer. Source code contains all the different chains:
https://github.com/sushiswap/sushiswap/blob/75219a75bfdb4ec8fa2d998b6535b0fd14017acc/packages/v2-sdk/src/constants.ts#L194
