### ISSUE TITLE
Where is the real migrations code? The code pushed to github is incomplete...

### ISSUE THREAD

**Issue by Oskii** [sushiswap/sushiswap#13]
Cannot deploy SushiSwap on truffle / ganache for testing purposes.

`truffle migrate` does not deploy anything, because there is nothing inside the `2_deploy_contracts.js` to deploy

What is the correct deployment order? The migration scripts on the official github do not have any contract deployment within them, please publish the correct code, or let me know how I can set this up for testing.

**Comment by iquanduan** [comment]
same

**Comment by MisterBanano** [comment]
Please, some one can push the code...

**Comment by Liberalite** [comment]
I tried to reproduce the migration but i'm doing something wrong... I posted on a question on Stackoverflow and will provide the migration code a bit later, after I find something that is actually helpful, I'm still trying to make it work but I see that even after depositing that accSushiPerShare is still 0 in every pool.

Here is the link on Stackoverflow: https://ethereum.stackexchange.com/questions/87651/sushiswap-inner-workings

**Comment by matthewnolan** [comment]
Good post Liberalite, I too would love to see the migrations code

**Comment by oscarmartj** [comment]
> I tried to reproduce the migration but i'm doing something wrong... I posted on a question on Stackoverflow and will provide the migration code a bit later, after I find something that is actually helpful, I'm still trying to make it work but I see that even after depositing that accSushiPerShare is still 0 in every pool.
> 
> Here is the link on Stackoverflow: https://ethereum.stackexchange.com/questions/87651/sushiswap-inner-workings

Oh thanks. If you get it, we would appreciate it if you could share it here.

**Comment by hortonelectric** [comment]
@Liberalite did you get anything for this?

**Comment by Liberalite** [comment]
Not really, it semi-works on Solidity =0.6.6; but still 0 yield 🥴

After a lot of days of trying different things and going about watching all Tutorials and all I could find on Uniswap and starting to compare files for different projects, I learned that the original UniswapFactory is deployed using multiple versions ranging from `^0.5.0` to `=0.5.16`, that Sushi Factory & Router have been upgraded by @chefnomi, key takeaways are that he added the migrator inside his UniswapV2Factory and created a create2 function inside the UniswapV2Library that is used inside the Router to match the deployed Factory. Made a small update explaining more on Stackoverflow... still experimenting by myself and failing in a good way 😂

**Comment by roblof97** [comment]
any luck with this?

**Comment by bartjman** [comment]
The correct way to deploy right now is to use the versions you find on Etherscan, unless there are useful updates in this repo and manually deploy and link together the web of contracts ;) Or someone could take the time and fix this all up and create a migration and some tests...

**Comment by hortonelectric** [comment]
I have nearly completed a migration setup with truffle even though the tool
is a bit unwieldy.... Could use some help if anyone is interested contact me

**Comment by Oskii** [comment]
I have successfully clones this project and written my own migrations for it, but would be nice to have an official release...

**Comment by matthewlilley** [comment]
@Oskii, there already is. Check the deploy folder and have fun ;)

**Comment by ockang** [comment]
Hello community, did it work for you?

**Comment by ockang** [comment]
![image](https://user-images.githubusercontent.com/4240285/108612576-d26b1100-73e1-11eb-91ec-18e7b76b8bde.png)

Hello community, I tried cloning and deploying in the kovan network.

Everything works perfect, my question is.

1. With the code created, are you already alone to configure the sushiswap frontend and will it work?

**Comment by mirzausman371** [comment]
> @Oskii, there already is. Check the deploy folder and have fun ;)

Hi, @Oskii  I'm trying to migrate the liquidity from one router to another in the Ropsten network but when I try to run the MigratewithPermit Function, I got the execution reverted error. 

I've added the testnet tokens pair in one router and trying to move my liquidity to another router. Is there something I'm missing?

**Comment by Oskii** [comment]
Thanks :) I made this question over a year ago and then created an entire DeFi suite of tools including a DEX, but also the cheapest cross-chain bridge currently available (Umbria Narni Bridge). Thanks for the response

**Comment by mirzausman371** [comment]
Great, Are you able to Migrate the liquidity from one router to another?

**Comment by Oskii** [comment]
Why not user the Migrator.sol contract? Are you trying to do a liquidity
attack?

**Comment by mirzausman371** [comment]
Yes, I'm Playing around and want to test that. Do I need to set the Migrator in my Factory contract?

If you've Applied this, then can you please refer to any open source repo?
Thanks
