### ISSUE TITLE
How is a LP created?

### ISSUE THREAD

**Issue by GildedHonour** [sushiswap/sushiswap#133]
A liquidity pool is usually a pair, that is, 2 tokens, right? Then why is here there's only one:

https://github.com/sushiswap/sushiswap/blob/canary/test/MasterChef.test.ts

```
  context("With ERC/LP token added to the field", function () {
    beforeEach(async function () {
      this.lp = await this.ERC20Mock.deploy("LPToken", "LP", "10000000000") // only 1 token?
     //.......

```

Or does the 1st token get added into a newly liquidity pool implicitly? If so, what is that 1st token? SushiToken? 

How does one create a liquidity pool? How to add liquidity to it? How to withdraw liquidity from and  destroy it?  

As a developer I mean -- in Javascript/Typescript.

**Comment by matthewlilley** [comment]
A users share of a liquidity pool is represented as an lp token. An lp token is given by an AMM when adding liquidity of 2 tokens to a pool.

**Comment by GildedHonour** [comment]
And?
