### ISSUE TITLE
publish the newest `sushi` package

### ISSUE THREAD

**Issue by rouzwelt** [sushiswap/sushiswap#1413]
### Discussed in https://github.com/sushiswap/sushiswap/discussions/1411

<div type='discussions-op-text'>

<sup>Originally posted by **rouzwelt** April 14, 2024</sup>
at the moment the published `sushi` package v3.0.0 doesnt have all the updates up until newest main branch commits. so I was wondering if we can have a new release for sushi package.
other thing is that the sushi package has some other sub-packages that are not published as part of the sushi package in npm, only ceratin sub-packages are available on npm, so would be great if those other packages end up in the release as well.</div>

**Comment by matthewlilley** [comment]
@rouzwelt 3.1.0 has been published, will expect more regular versions from now on
