### ISSUE TITLE
refactor(Wagmi): CurrencyInput and BalanceController

### ISSUE THREAD

**Issue by chillichelli** [sushiswap/sushiswap#153]
Once Wagmi has multicall support, refactor the BalanceController, useWalletBalance and the CurrencyInput. All these components are currently inside the Furo app but should be moved to the @sushiswap/wagmi package when multicall is available

**Comment by OlaStenberg** [comment]
https://wagmi.sh/docs/hooks/useContractInfiniteReads

**Comment by chillichelli** [comment]
Hooks got implemented but wagmi has some instability issues that need resolving first.

**Comment by chillichelli** [comment]
Fixed
