### ISSUE TITLE
Back button isn't hidden on mobile when at the start, and if clicked explodes app.

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#168]
[![Screenshot_2022-06-11_14-22-13.png](https://mrkr.io/s/62a4a5154e4e9b11c994b4e0/2)](https://mrkr.io/s/62a4a5154e4e9b11c994b4e0/0)

Steps to reproduce: Open vesting on mobile and click back button.

Actual result: Back button shows even though at the start. If clicked, will cause app to explode.

Expected result: Back button doesn't show when at start on mobile, and explode when clicked.

---

**Reported by:** Matthew Lilley (matthew@sushi.com)

**Source URL:** [https://sushi.com/furo/vesting/1?chainId=1](https://sushi.com/furo/vesting/1?chainId=1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a4a5154e4e9b11c994b4e5_172444a8a9ff7b92)

**Console:** [ℹ️  1 info 📃  1 log ](https://app.marker.io/i/62a4a5154e4e9b11c994b4e5_172444a8a9ff7b92?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.63</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>Windows 14.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>598 x 1289</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a4a5154e4e9b11c994b4e5_172444a8a9ff7b92) - This issue was marked as resolved in Marker.io.
