### ISSUE TITLE
Missing _moveDelegates call in SushiToken transfer method?

### ISSUE THREAD

**Issue by NadiaSama** [sushiswap/sushiswap#17]
HI there is  _moveDelegates call in COMP transfer method. but SushiToken does not.

https://github.com/compound-finance/compound-protocol/blob/master/contracts/Governance/Comp.sol#L117
https://github.com/compound-finance/compound-protocol/blob/master/contracts/Governance/Comp.sol#L241

**Comment by bartjman** [comment]
We're not using the compound governance at all... I think it was planned, but never used. It's just baggage now.
