### ISSUE TITLE
Wallet dropdown hidden on swap widget

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#184]
[![Screenshot_2022-06-26_06-26-08.png](https://mrkr.io/s/62b7fc00c0839fbb77934bb9/2)](https://mrkr.io/s/62b7fc00c0839fbb77934bb9/0)

Steps to reproduce: Open swap without connect wallet

Actual result: Wallet dropdown not visible

Expected result: Wallet dropdown should be visible

---

**Source URL:** [https://sushiswap-git-feature-sushixswap-teamsushi.vercel.app/swap?srcChainId=43114&dstChainId=10&srcToken=0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=&dstTypedAmount=&srcUseBentoBox=false&dstUseBentoBox=false](https://sushiswap-git-feature-sushixswap-teamsushi.vercel.app/swap?srcChainId=43114&dstChainId=10&srcToken=0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=&dstTypedAmount=&srcUseBentoBox=false&dstUseBentoBox=false)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b7fc00c0839fbb77934bc2_00b2b594282e1278)

**Console:** [ℹ️  1 info 📃  5 logs ](https://app.marker.io/i/62b7fc00c0839fbb77934bc2_00b2b594282e1278?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>Windows 14.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560 x 1289</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b7fc00c0839fbb77934bc2_00b2b594282e1278) - This issue was marked as resolved in Marker.io.
