### ISSUE TITLE
No route handling missing

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#193]
[![Screenshot_2022-07-05_11-41-52.png](https://mrkr.io/s/62c42380dc2ef4a67757278e/2)](https://mrkr.io/s/62c42380dc2ef4a67757278e/0)

Steps to reproduce: Choose AVAX (Avalance) -> Aave (Optimism)

Actual result: Constantly shows fetching price, and allows you to click swap despite no route.

Expected result: Swap should be disabled and insufficient liquidity should be shown

---

**Source URL:** [https://sushiswap-git-feature-sushixswap-teamsushi.vercel.app/swap?srcToken=0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7&dstChainId=10&dstUseBentoBox=false&dstToken=0x76FB31fb4af56892A25e32cFC43De717950c9278&srcTypedAmount=1&dstTypedAmount=&srcChainId=43114&srcUseBentoBox=false](https://sushiswap-git-feature-sushixswap-teamsushi.vercel.app/swap?srcToken=0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7&dstChainId=10&dstUseBentoBox=false&dstToken=0x76FB31fb4af56892A25e32cFC43De717950c9278&srcTypedAmount=1&dstTypedAmount=&srcChainId=43114&srcUseBentoBox=false)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c42380dc2ef4a6775727fe_db994c94f01f849b)

**Console:** [⚠️  20 warnings 📃  88 logs ](https://app.marker.io/i/62c42380dc2ef4a6775727fe_db994c94f01f849b?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>Windows 14.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560 x 1289</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c42380dc2ef4a6775727fe_db994c94f01f849b) - This issue was marked as resolved in Marker.io.
