### ISSUE TITLE
Approve button spacing

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#194]
[![Screenshot_2022-07-05_11-43-56.png](https://mrkr.io/s/62c423fce806e5a94a380312/2)](https://mrkr.io/s/62c423fce806e5a94a380312/0)

Steps to reproduce: Select token which needs approving

Actual result: Approve sat to close to swap button

Expected result: Breathing room for approve

---

**Source URL:** [https://sushiswap-git-feature-sushixswap-teamsushi.vercel.app/swap?srcToken=0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E&dstChainId=10&dstUseBentoBox=false&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=1&dstTypedAmount=0.000901942050111982&srcChainId=43114&srcUseBentoBox=false](https://sushiswap-git-feature-sushixswap-teamsushi.vercel.app/swap?srcToken=0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E&dstChainId=10&dstUseBentoBox=false&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=1&dstTypedAmount=0.000901942050111982&srcChainId=43114&srcUseBentoBox=false)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c423fce806e5a94a380387_eb6e4f76d3cb8ead)

**Console:** [⚠️  14 warnings 📃  100 logs ](https://app.marker.io/i/62c423fce806e5a94a380387_eb6e4f76d3cb8ead?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>Windows 14.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560 x 1289</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by chillichelli** [comment]
Cabbage is going to create a new design for having multiple buttons and showing how many there are instead of laying out all the buttons

**Comment by chillichelli** [comment]
Fixed for now until redesign
