### ISSUE TITLE
No visual when swap on only one side

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#195]
[![Screenshot_2022-07-05_11-49-53.png](https://mrkr.io/s/62c42561dc2ef4a677572e70/2)](https://mrkr.io/s/62c42561dc2ef4a677572e70/0)

Steps to reproduce: Choose bridge token USDC on Avalance, and ETH on optimism. This means that a swap will only happen on the destination.

Actual result: No visual shown

Expected result: Visual shown

---

**Source URL:** [https://sushiswap-git-feature-sushixswap-teamsushi.vercel.app/swap?srcToken=0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E&dstChainId=10&dstUseBentoBox=false&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=1&dstTypedAmount=0.000901942050111982&srcChainId=43114&srcUseBentoBox=false](https://sushiswap-git-feature-sushixswap-teamsushi.vercel.app/swap?srcToken=0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E&dstChainId=10&dstUseBentoBox=false&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=1&dstTypedAmount=0.000901942050111982&srcChainId=43114&srcUseBentoBox=false)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c42561dc2ef4a677572ee4_03ddf54f50d83c47)

**Console:** [⚠️  15 warnings 📃  98 logs ](https://app.marker.io/i/62c42561dc2ef4a677572ee4_03ddf54f50d83c47?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>Windows 14.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560 x 1289</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c42561dc2ef4a677572ee4_03ddf54f50d83c47) - This issue was marked as resolved in Marker.io.
