### ISSUE TITLE
Support for Changing Chain

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#198]
[![Screenshot_2022-07-06_08-45-41.png](https://mrkr.io/s/62c54bb5f17e4939cfd82079/2)](https://mrkr.io/s/62c54bb5f17e4939cfd82079/0)

Steps to reproduce:

N/A

Actual result:

Have to change chains from Metasmask.

Expected result:

It would be good to give option to change chain, like we did for sushi 1.0 UI

---

**Source URL:** [https://sushi.com/furo/dashboard](https://sushi.com/furo/dashboard)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c54bb5f17e4939cfd8207c_28a85687a3009480)

**Console:** [📃  0 logs](https://app.marker.io/i/62c54bb5f17e4939cfd8207c_28a85687a3009480?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 984</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by chillichelli** [comment]
Hmmm, wdyt @matthewlilley ?

**Comment by sarangparikh22** [comment]
I would like that, changing from metamask is a bit annoying, having an option on the app, makes it easier, but if we are planning to depreciate it, then probably this a non issue.

**Comment by matthewlilley** [comment]
Furo shold act as a cross chain app by default, as a user you should be able to see all streams & vestings across networks from a single dashboard, and only forced to switch chain when you're about to do an action e.g. withdraw.

However, at creation you need to know what network you want to stream a stream etc... on, so probably adding a chain option here is what's needed? And then before pressing create it would ask you to switch chain. 

Wdyt?

**Comment by sarangparikh22** [comment]
I think we should have the multichain UI, but we should also give the chain selector on top, the chain selector will not filter anything for view operation, however for write operations, such as create stream, vesting e.t.c. The user can change. Adding the selector on the top right, gives users always the reminder on what chain they are, obviously now when our app becomes multichain, they can see data from all the chains. Additionally, in the view, there should be filters, to filter the chains, helping sort the content for the viewer better.

**Comment by chillichelli** [comment]
I guess it wouldnt hurt to add a network selector

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by matthewlilley** [comment]
Completed

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c54bb5f17e4939cfd8207c_28a85687a3009480) - This issue was marked as **✅ Resolved** in Marker.io
