### ISSUE TITLE
'Create Vesting' field validation doesn't work

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#200]
[![Screenshot_2022-07-08_21-24-34.png](https://mrkr.io/s/62c8a092f17e4939cfe1fda2/2)](https://mrkr.io/s/62c8a092f17e4939cfe1fda2/0)

Steps to reproduce:
Create Vesting > Input start date '5 mins from now' > Review > Wait for more than 5 mins and then click 'create vesting'

Actual result:
Web app has no response

Expected result:
show error message that says start time has expired

---

**Source URL:** [https://sushi.com/furo/vesting/create](https://sushi.com/furo/vesting/create)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c8a092f17e4939cfe1fda5_d6244887fb1cda14)

**Console:** [📃  0 logs](https://app.marker.io/i/62c8a092f17e4939cfe1fda5_d6244887fb1cda14?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.53</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1385 x 798</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c8a092f17e4939cfe1fda5_d6244887fb1cda14) - This issue was marked as resolved in Marker.io.
