### ISSUE TITLE
Input isn't auto revalidating when currency changes

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#208]
[![Screenshot_2022-07-14_09-14-38.png](https://mrkr.io/s/62cfde7e1f50aae86f9eefc4/2)](https://mrkr.io/s/62cfde7e1f50aae86f9eefc4/0)

Steps to reproduce: Select currency where you dont have a balance so the insufficient funds input validation shows, and then switch to another when you have a balance.

Actual result: Input still says insufficient balance

Expected result: Revalidate and no input error

---

**Source URL:** [https://furo-git-feature-token-approval-system-v2-teamsushi.vercel.app/furo/stream/create/single](https://furo-git-feature-token-approval-system-v2-teamsushi.vercel.app/furo/stream/create/single)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62cfde7e1f50aae86f9eefc7_146a18f6960f810c)

**Console:** [📃  0 logs](https://app.marker.io/i/62cfde7e1f50aae86f9eefc7_146a18f6960f810c?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>Windows 14.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560 x 1321</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62cfde7e1f50aae86f9eefc7_146a18f6960f810c) - This issue was marked as **✅ Resolved** in Marker.io
