### ISSUE TITLE
Use 'Unlocked' instead of "Streamed" for vesting

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#211]
[![Screenshot_2022-07-16_00-34-08.png](https://mrkr.io/s/62d20780dc2ef4a677780ea7/2)](https://mrkr.io/s/62d20780dc2ef4a677780ea7/0)

---

**Source URL:** [https://sushi.com/furo/vesting/5?chainId=5](https://sushi.com/furo/vesting/5?chainId=5)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d20780dc2ef4a677780eaa_a0c5abb8cfaebeb6)

**Console:** [📃  0 logs](https://app.marker.io/i/62d20780dc2ef4a677780eaa_a0c5abb8cfaebeb6?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.53</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1360 x 798</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d20780dc2ef4a677780eaa_a0c5abb8cfaebeb6) - This issue was marked as resolved in Marker.io.
