### ISSUE TITLE
Cross chain swap white background

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#212]
[![Screenshot_2022-07-16_15-51-01.png](https://mrkr.io/s/62d2de65e806e5a94a59bdf3/2)](https://mrkr.io/s/62d2de65e806e5a94a59bdf3/0)

Steps to reproduce:
land on sushi.com/swap

Actual result:

has white glow flashing for 1 sec

Expected result:
no white glow at all in the background

---

**Source URL:** [https://sushi.com/swap?srcChainId=43114&dstChainId=10&srcToken=0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=&dstTypedAmount=&srcUseBentoBox=false&dstUseBentoBox=false](https://sushi.com/swap?srcChainId=43114&dstChainId=10&srcToken=0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=&dstTypedAmount=&srcUseBentoBox=false&dstUseBentoBox=false)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d2de65e806e5a94a59bdf6_c8eb08ab2a23444c)

**Console:** [📃  0 logs](https://app.marker.io/i/62d2de65e806e5a94a59bdf6_c8eb08ab2a23444c?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.53</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1360 x 798</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by 0xcabbage** [comment]
this shows up when opening sushi.com/furo too on the bottom of the page

**Comment by chillichelli** [comment]
Got fixed

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d2de65e806e5a94a59bdf6_c8eb08ab2a23444c) - This issue was marked as resolved in Marker.io.
