### ISSUE TITLE
Dashboard Tabs: Memorize users' last choice

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#216]
[![Screenshot_2022-07-18_17-18-36.png](https://mrkr.io/s/62d595eceaf0f4eddf353c9c/2)](https://mrkr.io/s/62d595eceaf0f4eddf353c9c/0)

Expected result:

Default tabs shown - Incoming / Outgoing (Incoming as the active tab)

Once users have selected outgoing as the active tab and left it there, next time they come back 'outgoing' should remain as the active tab

---

**Source URL:** [https://sushi.com/furo/dashboard](https://sushi.com/furo/dashboard)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d595eceaf0f4eddf353c9f_7db324d147de6c32)

**Console:** [📃  0 logs](https://app.marker.io/i/62d595eceaf0f4eddf353c9f_7db324d147de6c32?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.53</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1379 x 800</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d595eceaf0f4eddf353c9f_7db324d147de6c32) - This issue was marked as **✅ Resolved** in Marker.io
