### ISSUE TITLE
Record initial Furo Stream amount so we can track interest accrued

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#218]
Ola is going to add intial amount to subgraph, we can then track interest accrued since stream start.

**Comment by OlaStenberg** [comment]
@chillichelli
Deployed subgraphs on sushi-labs, feel free to continue on https://github.com/sushiswap/sushiswap/tree/feature/furo-integrate-merged-subgraph

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by matthewlilley** [comment]
Completed
