### ISSUE TITLE
Custom slippage is using Numeric input instead of Percentage input

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#223]
[![Screenshot_2022-07-20_01-17-40.png](https://mrkr.io/s/62d757b4e806e5a94a60f203/2)](https://mrkr.io/s/62d757b4e806e5a94a60f203/0)

Actual result:

unable to set slippage to be less than 1%

Expected result:

range should be >0%

*also settings window should be longer to avoid scroll bar

---

**Source URL:** [https://sushi.com/swap?srcChainId=43114&dstChainId=10&srcToken=0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=0.1&dstTypedAmount=&srcUseBentoBox=false&dstUseBentoBox=false](https://sushi.com/swap?srcChainId=43114&dstChainId=10&srcToken=0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7&dstToken=0x4200000000000000000000000000000000000006&srcTypedAmount=0.1&dstTypedAmount=&srcUseBentoBox=false&dstUseBentoBox=false)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d757b4e806e5a94a60f206_85f5b6a8803771ac)

**Console:** [📃  0 logs](https://app.marker.io/i/62d757b4e806e5a94a60f206_85f5b6a8803771ac?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.53</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1380 x 800</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by chillichelli** [comment]
Wait for https://github.com/sushiswap/sushiswap/pull/374 to get merged which adds percentage input

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d757b4e806e5a94a60f206_85f5b6a8803771ac) - This issue was marked as **✅ Resolved** in Marker.io
