### ISSUE TITLE
remove pink glow from the footer

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#224]
[![Screenshot_2022-07-20_16-46-14.png](https://mrkr.io/s/62d831560f746e3dcbe325a5/2)](https://mrkr.io/s/62d831560f746e3dcbe325a5/0)

Actual result:
there is a pink glow on sushi.com/furo

Expected result:
no pink glow

---

**Source URL:** [https://sushi.com/furo](https://sushi.com/furo)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d831560f746e3dcbe325a8_95d05b613f003403)

**Console:** [📃  0 logs](https://app.marker.io/i/62d831560f746e3dcbe325a8_95d05b613f003403?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.53</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 825</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d831560f746e3dcbe325a8_95d05b613f003403) - This issue was marked as resolved in Marker.io.
