### ISSUE TITLE
'View portfolio' doesn't always works

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#226]
[![Screenshot_2022-07-21_03-02-45.png](https://mrkr.io/s/62d8c1d50f746e3dcbe4459a/2)](https://mrkr.io/s/62d8c1d50f746e3dcbe4459a/0)

Steps to reproduce:
go to sushi.com/furo and click on account > view portfolio

Actual result:
sometimes it loads an empty page

Expected result:
always load account portfolio page

---

**Source URL:** [https://sushi.com/furo/dashboard](https://sushi.com/furo/dashboard)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d8c1d50f746e3dcbe4459d_ec9303e93af50f15)

**Console:** [📃  0 logs](https://app.marker.io/i/62d8c1d50f746e3dcbe4459d_ec9303e93af50f15?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.53</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 761</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by 0xcabbage** [comment]
https://user-images.githubusercontent.com/80417421/180120928-277608e7-4cd6-4111-8557-d96fd1655ad3.mp4

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by matthewlilley** [comment]
will remove this link

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d8c1d50f746e3dcbe4459d_ec9303e93af50f15) - This issue was marked as **✅ Resolved** in Marker.io
