### ISSUE TITLE
Shows Estimate Time on Same Chain

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#241]
[![Screenshot_2022-07-27_09-00-04.png](https://mrkr.io/s/62e0fe945ed55810306ef3e8/2)](https://mrkr.io/s/62e0fe945ed55810306ef3e8/0)

Steps to reproduce:
Select the src and dest as the same chain

Actual result:
Shows the estimated time.

Expected result:
It should not show the estimated time for the same chain

---

**Source URL:** [https://sushi.com/swap?srcToken=ETH&dstToken=0xd4d42F0b6DEF4CE0383636770eF773390d85c61A&srcChainId=42161&dstChainId=42161&srcTypedAmount=1](https://sushi.com/swap?srcToken=ETH&dstToken=0xd4d42F0b6DEF4CE0383636770eF773390d85c61A&srcChainId=42161&dstChainId=42161&srcTypedAmount=1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62e0fe945ed55810306ef3eb_87cc744d05ef79e5)

**Console:** [📃  0 logs](https://app.marker.io/i/62e0fe945ed55810306ef3eb_87cc744d05ef79e5?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 984</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by matthewlilley** [comment]
It shouldn't show an est. time on same chain at all @chillichelli
