### ISSUE TITLE
Middle external link icon needs to be removed or indicated inactive

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#253]
[![Screenshot_2022-08-01_15-55-02.png](https://mrkr.io/s/62e7f75661eb8244d2aefe9f/2)](https://mrkr.io/s/62e7f75661eb8244d2aefe9f/0)

Middle 'external link' icon for the stargate transaction link still shows its clickable even though its greyed out

Remove icon or say 'link coming soon'

---

**Source URL:** [https://sushi.com/swap?srcToken=AVAX&dstToken=ETH&srcChainId=43114&dstChainId=42161&srcTypedAmount=0.1](https://sushi.com/swap?srcToken=AVAX&dstToken=ETH&srcChainId=43114&dstChainId=42161&srcTypedAmount=0.1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62e7f75661eb8244d2aefea2_b5a64ff81c1738dd)

**Console:** [📃  0 logs](https://app.marker.io/i/62e7f75661eb8244d2aefea2_b5a64ff81c1738dd?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.53</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 825</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62e7f75661eb8244d2aefea2_b5a64ff81c1738dd) - This issue was marked as resolved in Marker.io.
