### ISSUE TITLE
Amount Selector is not needed for vsting

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#298]
[![Screenshot_2022-09-11_06-34-22.png](https://mrkr.io/s/631d816e213855a33bfbfef1/2)](https://mrkr.io/s/631d816e213855a33bfbfef1/0)

You don't need to show the user how much amount they want to withdraw as vesting will withdraw all the amount that can be claimed. So, you can remove the amount selector and just keep the wallet or bento selection on the UI

Steps to reproduce:
Go to any vesting, which has completed some steps.

Actual result:
Shows amount to withdraw from the vesting and to where

Expected result:
Only should show the where (bento or wallet)

---

**Source URL:** [https://sushi.com/furo/vesting/12?chainId=1](https://sushi.com/furo/vesting/12?chainId=1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/631d816e213855a33bfbfef5_ebbee1e5aeaa7d99)

**Console:** [📃  0 logs](https://app.marker.io/i/631d816e213855a33bfbfef5_ebbee1e5aeaa7d99?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 1011</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by chillichelli** [comment]
https://github.com/sushiswap/sushiswap/pull/299 fixes this

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/631d816e213855a33bfbfef5_ebbee1e5aeaa7d99) - This issue was marked as **✅ Resolved** in Marker.io
