### ISSUE TITLE
ETH token icon on Optimism display is wrong

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#300]
[![Screenshot_2022-09-13_08-17-50.png](https://mrkr.io/s/63203cae213855a33b02740a/2)](https://mrkr.io/s/63203cae213855a33b02740a/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Source URL:** [https://sushi.com/swap?srcToken=ETH&dstToken=ETH&srcChainId=1&dstChainId=10&srcTypedAmount=](https://sushi.com/swap?srcToken=ETH&dstToken=ETH&srcChainId=1&dstChainId=10&srcTypedAmount=)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63203cae213855a33b02740e_b0a46e79fb42b37f)

**Console:** [📃  0 logs](https://app.marker.io/i/63203cae213855a33b02740e_b0a46e79fb42b37f?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 825</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by matthewlilley** [comment]
Resolved

**Comment by sarangparikh22** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/63203cae213855a33b02740e_b0a46e79fb42b37f) - This issue was marked as **✅ Resolved** in Marker.io
