### ISSUE TITLE
Should the Update be shown if not owner?

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#306]
[![Screenshot_2022-09-19_08-24-47.png](https://mrkr.io/s/6328274f31af01ca047a305b/2)](https://mrkr.io/s/6328274f31af01ca047a305b/0)

Steps to reproduce:
Open any stream which you are not the owner of

Actual result:
Shows disabled

Expected result:
Should not show at all

The question is, showed it be even shown if the user is not the owner, as they don't have anything to do with Update, not sure why we have displayed and disabled.

---

**Source URL:** [https://sushi.com/furo/stream/1007?chainId=1](https://sushi.com/furo/stream/1007?chainId=1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6328274f31af01ca047a305f_75a26863ca97f90f)

**Console:** [📃  0 logs](https://app.marker.io/i/6328274f31af01ca047a305f_75a26863ca97f90f?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 1011</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6328274f31af01ca047a305f_75a26863ca97f90f) - This issue was marked as **✅ Resolved** in Marker.io
