### ISSUE TITLE
Hardhat/Ethers Question

### ISSUE THREAD

**Issue by pandichef** [sushiswap/sushiswap#31]
It seems like you all recently made a big change in your tooling i.e., truffle to hardhat/ethers.  Can you explain the context here?  What motivated this change?

**Comment by matthewlilley** [comment]
@pandichef There wasn't really a development environment configured before now. Yes Truffle was included in the package json, but nothing had ever been configured and no deployments written. After some research, hardhat seemed like a great option for developer experiance and productivity. It's been very popular across the board. We firstly configured BentoBox for Hardhat then decided to bring parity between the two projects. Hope this helps :)

**Comment by pandichef** [comment]
uniswap-v2-core uses ethersjs/waffle directly; tasks are managed via package.json scripts.  Is there anything specific that Hardhat offers on top of Uniswap's model?  Tbh, there seems to be a lot of black-box magic in Hardhat that doesn't conform to OOP norms.  I'm not against it per se; I'd just like to understand the pros and cons.  Thank you!

**Comment by matthewlilley** [comment]
@pandichef I can't speak for Uniswap but from my perspective HardHat has allowed us to set up a powerful and friendly cross-dev Ethereum environment, which anyone should be able to set up with minimal friction, not just those that are familiar with the codebase. 

If I was to list a few pros off the top of my head:

- Runtime Extendability
- Agnostic & Flexible (Easy to use Web3, Ethers, Truffle), you aren't really forced into one particular setup.
- Debugging
- Community

There's many more, some of the cons are applicable to other systems so it wouldn't really be fair to call it a hardhat specific con. I think there's a lot of work that could be done when it comes to Ethereum development environments in general.
