### ISSUE TITLE
Transactions on pool page

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#317]
Add transactions table on pool page using live queries

https://github.com/graphprotocol/graph-client/blob/main/docs/live.md

**Comment by njokuScript** [comment]
Hi @matthewlilley is this still an open task? would love to hop on it.

**Comment by matthewlilley** [comment]
@njokuScript earn app is undergoing some substantial changes at the moment so I'll close this for now. Thanks for offering though!
