### ISSUE TITLE
Invest>Sushi Bar UI bugs 

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#318]
[![Screenshot_2022-09-21_08-11-57.png](https://mrkr.io/s/632ac74c38ba846b1765b7eb/2)](https://mrkr.io/s/632ac74c38ba846b1765b7eb/0)

Issue One: 13.51 -> 13.51% ideally we show APY instead of APR

Issue Two: xsushi icon size is smaller than expected

Issue Three: Input boxes length should be be the same

reference:
https://www.figma.com/file/rDvPmr7wWuGCSI2O7EC399/Yield-2.0?node-id=1785%3A8672

---

**Source URL:** [https://pool-git-feature-pool-teamsushi.vercel.app/pool](https://pool-git-feature-pool-teamsushi.vercel.app/pool)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/632ac74d38ba846b1765b7ef_41faf8b796bf2fcb)

**Console:** [📃  0 logs](https://app.marker.io/i/632ac74d38ba846b1765b7ef_41faf8b796bf2fcb?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1435 x 794</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by matthewlilley** [comment]
Fixed the percent format.

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/632ac74d38ba846b1765b7ef_41faf8b796bf2fcb) - This issue was marked as **✅ Resolved** in Marker.io
