### ISSUE TITLE
Pool table filtering is mssing

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#319]
[![Screenshot_2022-09-21_08-27-37.png](https://mrkr.io/s/632acaf9ef3e9eff8a1d419f/2)](https://mrkr.io/s/632acaf9ef3e9eff8a1d419f/0)

need a filter for pool only,  pool with farm

https://www.figma.com/file/rDvPmr7wWuGCSI2O7EC399/Yield-2.0?node-id=1785%3A8672

---

**Source URL:** [https://pool-git-feature-pool-teamsushi.vercel.app/pool](https://pool-git-feature-pool-teamsushi.vercel.app/pool)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/632acaf9ef3e9eff8a1d41a3_0fb90b6eadcf4d9c)

**Console:** [📃  0 logs](https://app.marker.io/i/632acaf9ef3e9eff8a1d41a3_0fb90b6eadcf4d9c?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1435 x 794</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/632acaf9ef3e9eff8a1d41a3_0fb90b6eadcf4d9c) - This issue was marked as **✅ Resolved** in Marker.io
