### ISSUE TITLE
APR -> APY (time ranges)

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#320]
[![Screenshot_2022-09-21_08-33-39.png](https://mrkr.io/s/632acc63a3b7d66b7130d4a5/2)](https://mrkr.io/s/632acc63a3b7d66b7130d4a5/0)

Pool fee APY 24h/7d/30d is missing

Column APR better to show 'APY(time range)'

https://www.figma.com/file/rDvPmr7wWuGCSI2O7EC399/Yield-2.0?node-id=1785%3A9373

---

**Source URL:** [https://pool-git-feature-pool-teamsushi.vercel.app/pool](https://pool-git-feature-pool-teamsushi.vercel.app/pool)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/632acc63a3b7d66b7130d4a9_011d5ec53f554a0d)

**Console:** [📃  0 logs](https://app.marker.io/i/632acc63a3b7d66b7130d4a9_011d5ec53f554a0d?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1435 x 794</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by matthewlilley** [comment]
We only have APR avaialble at the moment, but will keep this open for future.
