### ISSUE TITLE
Swap>Connect Wallet state

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#321]
[![Screenshot_2022-09-21_08-35-33.png](https://mrkr.io/s/632accd5674276e383e256e3/2)](https://mrkr.io/s/632accd5674276e383e256e3/0)

button state should be 'connect wallet' when no wallet is connected

---

**Source URL:** [https://sushiswap-git-feature-pool-teamsushi.vercel.app/swap](https://sushiswap-git-feature-pool-teamsushi.vercel.app/swap)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/632accd5674276e383e256e7_2a697f127b22b98b)

**Console:** [📃  0 logs](https://app.marker.io/i/632accd5674276e383e256e7_2a697f127b22b98b?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1435 x 794</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by matthewlilley** [comment]
It says connect wallet once you enter an amount

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/632accd5674276e383e256e7_2a697f127b22b98b) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/632accd5674276e383e256e7_2a697f127b22b98b) - This issue was marked as **❗️ Open** in Marker.io

**Comment by matthewlilley** [comment]
resolved

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/632accd5674276e383e256e7_2a697f127b22b98b) - This issue was marked as **✅ Resolved** in Marker.io
