### ISSUE TITLE
Swap>Carbon Offset UI bugs

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#322]
[![Screenshot_2022-09-21_09-25-54.png](https://mrkr.io/s/632ad8a26cf842d8b45612ad/2)](https://mrkr.io/s/632ad8a26cf842d8b45612ad/0)

1. learn more is not coded but currently waiting for a link for it (if no link we can remove 'learn more')
2. Offset token can only be BCT so options are removed.

---

**Source URL:** [https://sushiswap-git-feature-pool-teamsushi.vercel.app/swap](https://sushiswap-git-feature-pool-teamsushi.vercel.app/swap)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/632ad8a26cf842d8b45612b1_dfb227efcc9756aa)

**Console:** [📃  0 logs](https://app.marker.io/i/632ad8a26cf842d8b45612b1_dfb227efcc9756aa?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1435 x 794</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by matthewlilley** [comment]
fixed in feature branch

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/632ad8a26cf842d8b45612b1_dfb227efcc9756aa) - This issue was marked as **✅ Resolved** in Marker.io
