### ISSUE TITLE
Pool breadcrumb showing pool address instead of pool name

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#326]
[![Screenshot_2022-09-23_12-10-34.png](https://mrkr.io/s/632da23ad2066d2de6ffb507/2)](https://mrkr.io/s/632da23ad2066d2de6ffb507/0)

0x..... -> ETH-USDC Classic Pool 0.05% in this case

---

**Source URL:** [https://pool-git-feature-pool-teamsushi.vercel.app/pool/arb1:0x905dfcd5649217c42684f23958568e533c711aa3/add](https://pool-git-feature-pool-teamsushi.vercel.app/pool/arb1:0x905dfcd5649217c42684f23958568e533c711aa3/add)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/632da23ad2066d2de6ffb50a_e6df15ca036b7a0b)

**Console:** [📃  0 logs](https://app.marker.io/i/632da23ad2066d2de6ffb50a_e6df15ca036b7a0b?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 825</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/632da23ad2066d2de6ffb50a_e6df15ca036b7a0b) - This issue was marked as **✅ Resolved** in Marker.io
