### ISSUE TITLE
Add automated CI

### ISSUE THREAD

**Issue by steffenix** [sushiswap/sushiswap#33]
I could help on adding automated CI test, formatting and coverage reports. 
Is that something the team is interested in?

**Comment by Clearwood** [comment]
we are definitely always happy for improvements in our flow, we do have some CI pipelines already

**Comment by steffenix** [comment]
I am not sure that was the case a month ago when I checked

**Comment by Clearwood** [comment]
> I am not sure that was the case a month ago when I checked

I know, please excuse the late reply.
