### ISSUE TITLE
Dynamic OG image API

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#334]
For various products and pages we'll want to show dynamic data within the OG (Open Graph) images:

![download](https://user-images.githubusercontent.com/6063350/192636551-8ac20097-b96b-4f4b-9c68-10c854e46858.png)

To achieve this we'll have to link the images to an API which returns this dynamic image data and a context type of it.

**Comment by matthewlilley** [comment]
https://twitter.com/vercel/status/1579561293069316096

**Comment by chillichelli** [comment]
@matthewlilley is this one done?
