### ISSUE TITLE
Can't set slippage to less than 1 after changing it

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#337]
[![Screenshot_2022-09-30_09-38-13.png](https://mrkr.io/s/6336b90549b7bf39ac912372/2)](https://mrkr.io/s/6336b90549b7bf39ac912372/0)

Steps to reproduce:
Go to slippage, update it above one, try to set it back to under 1. e.g. 0.5

Actual result:
Doesn't let us set it to < 1

Expected result:
Should allow us to set slippage back to < 1

---

**Source URL:** [https://www.sushi.com/swap](https://www.sushi.com/swap)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6336b90549b7bf39ac912375_3a6e9a2466bd08f6)

**Console:** [📃  0 logs](https://app.marker.io/i/6336b90549b7bf39ac912375_3a6e9a2466bd08f6?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 1011</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by matthewlilley** [comment]
duplicate

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6336b90549b7bf39ac912375_3a6e9a2466bd08f6) - This issue was marked as **✅ Resolved** in Marker.io
