### ISSUE TITLE
Confirm swap modal input amount is 1 unit less than expected

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#339]
[![Screenshot_2022-10-03_18-37-53.png](https://mrkr.io/s/633b2c011cf6498f2520f706/2)](https://mrkr.io/s/633b2c011cf6498f2520f706/0)

Steps to reproduce:
Enter input greater than 1 and click on swap

Actual result:
In the confirm swap shows the input value - 1 wei

Expected result:
It should the exact amount which was input

---

**Source URL:** [https://sushiswap-git-feature-stable-teamsushi.vercel.app/swap?chainId=10&token0=0x7F5c764cBc14f9669B88837ca1490cCa17c31607&input0=100&token1=0x94b008aA00579c1307B0EF2c499aD98a8ce58e58](https://sushiswap-git-feature-stable-teamsushi.vercel.app/swap?chainId=10&token0=0x7F5c764cBc14f9669B88837ca1490cCa17c31607&input0=100&token1=0x94b008aA00579c1307B0EF2c499aD98a8ce58e58)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/633b2c011cf6498f2520f709_f17d53c50d502ea4)

**Console:** [📃  0 logs](https://app.marker.io/i/633b2c011cf6498f2520f709_f17d53c50d502ea4?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 1011</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/633b2c011cf6498f2520f709_f17d53c50d502ea4) - This issue was marked as **✅ Resolved** in Marker.io
