### ISSUE TITLE
Celo compat SushiSwapV2Router02

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#357]
Would be better not to have to deal with weirdness in UI just for CELO.

**Comment by sarangparikh22** [comment]
@matthewlilley The interface for the ```function addLiquidity(
        address tokenA,
        address tokenB,
        uint amountADesired,
        uint amountBDesired,
        uint amountAMin,
        uint amountBMin,
        address to,
        uint deadline
    )``` is different for the ```function addLiquidityETH(
        address token,
        uint amountTokenDesired,
        uint amountTokenMin,
        uint amountETHMin,
        address to,
        uint deadline
    )``` you would still have to make a special case with celo. Was that the issue?

**Comment by matthewlilley** [comment]
addLiquidityETH needs to handle CELO in a different way, since there's no WCELO, native CELO itself can act like an ERC20

**Comment by sarangparikh22** [comment]
#380
