### ISSUE TITLE
My Liquidity Position is shown wrong

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#361]
[![Screenshot_2022-10-04_09-06-12.png](https://mrkr.io/s/633bf784faf3ea7972aad78f/2)](https://mrkr.io/s/633bf784faf3ea7972aad78f/0)

Steps to reproduce:
Add liquidity for a pair, do some swaps on that particular pair

Actual result:
It doesn't show the correct position and underlying token value of the LP

Expected result:
It should the actual value of the underlying tokens as shown in the correct arrow

---

**Source URL:** [https://invest-git-feature-stable-teamsushi.vercel.app/earn/oeth:0xb64a3dd479cb9fc35cc8e5ad7e27ffbf5fb0d597/remove](https://invest-git-feature-stable-teamsushi.vercel.app/earn/oeth:0xb64a3dd479cb9fc35cc8e5ad7e27ffbf5fb0d597/remove)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/633bf784faf3ea7972aad792_e32beaf9e59750f8)

**Console:** [📃  0 logs](https://app.marker.io/i/633bf784faf3ea7972aad792_e32beaf9e59750f8?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 1011</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by chillichelli** [comment]
This is because of slippage

**Comment by matthewlilley** [comment]
fixed

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/633bf784faf3ea7972aad792_e32beaf9e59750f8) - This issue was marked as **✅ Resolved** in Marker.io
