### ISSUE TITLE
Boba logo is rendering wierd periodically

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#372]
[![Screenshot_2022-10-05_01-14-50.png](https://mrkr.io/s/633cda8ad1f981bf0976e028/2)](https://mrkr.io/s/633cda8ad1f981bf0976e028/0)

Boba logo is rendering wierd periodically

---

**Source URL:** [https://www.sushi.com/earn?networks=2222](https://www.sushi.com/earn?networks=2222)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/633cda8ad1f981bf0976e02d_7d0ef2dba07b0e19)

**Console:** [ℹ️  1 info 📃  1 log ](https://app.marker.io/i/633cda8ad1f981bf0976e02d_7d0ef2dba07b0e19?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>5120 x 1440</td></tr><tr><td><strong>OS</strong></td><td>Windows 14.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1650 x 1240</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by LufyCZ** [comment]
@matthewlilley I've already noticed and tried fixing this bug a couple weeks ago, have no idea what causes it

**Comment by chillichelli** [comment]
I cant reproduce this on my machine
