### ISSUE TITLE
Add Furo page to analytics app

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#386]
Add Furo page to analytics app

- A token list similarly to https://www.sushi.com/analytics "Top Tokens" view
- A couple of KPIs at the top, TVL, token count & user count

**Comment by OlaStenberg** [comment]
@LufyCZ Added token snapshots to furo and deployed them it to subgraphs at sushi-subgraphs/furo-<NETWORK> 

I check the data and couldn't see anything wrong with it, but please confirm once you have rendered it and if it looks good

Added `TokenHourSnapshot` and `TokenDaySnapshot`
```graphql
...
cumulativeLiquidityShares: BigInt!
cumulativeLiquidityAmount: BigInt!
```
Should use the amount, just added shares as a "nice to have"
