### ISSUE TITLE
Sitemaps

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#412]
Add sitemaps to earn, analytics, furo, etc... and add a github workflow to regenerate them

**Comment by LufyCZ** [comment]
> Add sitemaps to earn, analytics, furo, etc... and add a github workflow to regenerate them

github workflow to regenerate?
they regenerate either on build, or dynamically based on an api call

**Comment by matthewlilley** [comment]
ah yeah, just get coverage on earn & analytics then since they have a lot of extra pages
