### ISSUE TITLE
Linking Custom Tokens is Broken

### ISSUE THREAD

**Issue by mcorrig4** [sushiswap/sushiswap#420]
The new GET query API seems to be failing for tokens that are not in the default Sushi tokens list.

For example, lqETH/WETH is the 12th largest market on Arbitrum (by TVL) but the swap link defaults to wBTC as the second token instead of lqETH:
https://www.sushi.com/swap?token0=0x82aF49447D8a07e3bd95BD0d56f35241523fBab1&token1=0x73700aeCfC4621E112304B6eDC5BA9e36D7743D3&chainId=42161

![image](https://user-images.githubusercontent.com/1342367/195905571-33643c26-caef-4715-ba83-c9b31de55120.png)

This issue persists even after adding the contract addresses to my custom tokens list.

**Comment by matthewlilley** [comment]
@mcorrig4 Thanks for the heads up. I know what's probably causing this, I'll take a look now.
