### ISSUE TITLE
Links Broken

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap#423]
[![Screenshot_2022-10-15_23-27-56.png](https://mrkr.io/s/634b41fcac6eefdd4f9afa30/2)](https://mrkr.io/s/634b41fcac6eefdd4f9afa30/0)

Steps to reproduce:
Go to sushi.com/swap and click on xswap or earn

Actual result:
404 since the next link is getting added to the current path instead of replacing the path

Expected result:
Should update the url and open the page

---

**Source URL:** [https://www.sushi.com/swap/xswap](https://www.sushi.com/swap/xswap)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/634b41fcac6eefdd4f9afa33_9c15615415b4c2f5)

**Console:** [📃  0 logs](https://app.marker.io/i/634b41fcac6eefdd4f9afa33_9c15615415b4c2f5?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 960</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by chillichelli** [comment]
Seems to be fixed

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/634b41fcac6eefdd4f9afa33_9c15615415b4c2f5) - This issue was marked as **✅ Resolved** in Marker.io
