### ISSUE TITLE
What is the router address on Kovan?

### ISSUE THREAD

**Issue by HeyWeiPan** [sushiswap/sushiswap#49]
Hey guys i see that routerV2 address for Kovan is 0x027Bb5f9205360aC628C33508c3f182320A44525 from https://github.com/sushiswap/sushiswap/blob/master/deployments/kovan/UniswapV2Router02.json and from https://dev.sushiswap.fi/sushiswap/contracts. But it seems that this address is not correct. I can run the same code with a uniswap router address but not this address. Can you confrim the address?

**Comment by Clearwood** [comment]
@matthewlilley

**Comment by matthewlilley** [comment]
https://dev.sushi.com/sushiswap/contracts#sushiv-2-router02-1

**Comment by HeyWeiPan** [comment]
thanks man
