### ISSUE TITLE
Network filter doesnt work as intended

### ISSUE THREAD

**Issue by 0xcabbage** [sushiswap/sushiswap#494]
[![Screenshot_2022-11-01_14-45-05.png](https://mrkr.io/s/636130f1231c20e6328559ad/2)](https://mrkr.io/s/636130f1231c20e6328559ad/0)

After filter selection, it doesn't show the filter status. 

---

**Source URL:** [https://www.sushi.com/earn](https://www.sushi.com/earn)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/636130f1231c20e6328559b0_4178b4f3ef417dcf?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/636130f1231c20e6328559b0_4178b4f3ef417dcf?advanced=1&activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 107.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.5.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 825</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by chillichelli** [comment]
Fixed

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/636130f1231c20e6328559b0_4178b4f3ef417dcf) - This issue was marked as **✅ Resolved** in Marker.io
