### ISSUE TITLE
Multiple Ownable & ERC20, IMigratorChef duplicates

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap#71]
We have a situation where we're generating multiple types for multiple contracts with duplicate names, causing a collision. More recently more have been popping up, we should figure out a way to solve this.

![Screenshot_38](https://user-images.githubusercontent.com/6063350/113472972-75da2780-945e-11eb-822e-70a34432a4ef.png)

**Comment by matthewlilley** [comment]
Also, somewhat unrelated, but I think that the Mocks should not be included here.

**Comment by wlawt** [comment]
Hi! Is this still available? Also wondering how to possibly get started with this as well :)

**Comment by aqeelahcodes** [comment]
https://stackoverflow.com/questions/2411213/wcf-multiple-contracts-with-duplicate-method-names

**Comment by matt-user** [comment]
Hi,  I'm interested in fixing this issue if it is still open.  I understand that this is a name collision issue, but not much more beyond that.  Could you point me to where the duplicate names are being generated?  Would it also be possible to point me to where the name collisions occur?
