### ISSUE TITLE
Redundant Calculation

### ISSUE THREAD

**Issue by tanliwei** [sushiswap/sushiswap#73]
There are redundant calculation of `amountIn.mul(997)` in the function `_swap` of contract `SushiMaker.sol`, why not replace its calculation by the viariable `amountInWithFee` which stores the result of `amountIn.mul(997)`. 
Is there any special reason?

https://github.com/sushiswap/sushiswap/blob/414f55587c25b4a761f402d29995aded08806da2/contracts/SushiMaker.sol#L222-L253

**Comment by boringcrypto** [comment]
Yeah, just a leftover from several refactors...

**Comment by tanliwei** [comment]
@boringcrypto I see, here is a PR for this tiny update: https://github.com/sushiswap/sushiswap/pull/86
