### ISSUE TITLE
操你妈的，祝你感染COVID-19，下地狱去吧

### ISSUE THREAD

**Issue by cdscawd** [sushiswap/sushiswap#8]

**Comment by Tabby85** [comment]
> _No description provided._

https://github.com/sushiswap/sushiswap/issues/8#issue-694262912

**Comment by love-fay** [comment]
💐💐💐💐💐💐💐
💐💐💐💐💐💐💐
💐💐💐💐💐💐💐
💐💐💐💐💐💐💐
💐💐💐💐💐💐💐
💐💐💐💐💐💐💐

**Comment by TT1943** [comment]
我顶你个肺

**Comment by Tabby85** [comment]
#

**Comment by Tabby85** [comment]
https://github.com/sushiswap/sushiswap/issues/8#issuecomment-689278833

**Comment by Tabby85** [comment]
> > _No description provided._
> 
> [#8 (comment)](https://github.com/sushiswap/sushiswap/issues/8#issue-694262912)

**Comment by Tabby85** [comment]
@love-fay

**Comment by Tabby85** [comment]
@cdscawd

**Comment by Tabby85** [comment]
@Tabby85

**Comment by huwentao1** [comment]
暴躁老哥

**Comment by cdscawd** [comment]
你终于承认你的做法有问题了！而我已经被你割了！
