### ISSUE TITLE
Potential reentrancy 

### ISSUE THREAD

**Issue by Yuannan97** [sushiswap/sushiswap#90]
It seems that functions like `updatePool ` are vulnerable to reentrancy attack.  If a malicious LPtoken is added, sushiswap may suffer from this.
Why do not use `nonReentrant` modifier to ensure functions like `updatePool` to be safe to reentrancy attack?

**Comment by EngineEarz** [comment]
> It seems that functions like `updatePool ` are vulnerable to reentrancy attack. If a malicious LPtoken is added, sushiswap may suffer from this. Why do not use `nonReentrant` modifier to ensure functions like `updatePool` to be safe to reentrancy attack?

sup contact me at eduation finance on twiiter  lets collab
